routes/web.php
<?php

use App\Http\Controllers\Admin\CampusController;
use App\Http\Controllers\Admin\CarruselController;
use App\Http\Controllers\Admin\CompeticionController;
use App\Http\Controllers\Admin\FichaJugadorController;
use App\Http\Controllers\Admin\GaleriaNavidadController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\Info_CampusController;
use App\Http\Controllers\Admin\Info_NavidadController;
use App\Http\Controllers\Admin\Info_ReservaController;
use App\Http\Controllers\Admin\NoticiasController;
use App\Http\Controllers\Admin\PatrocinadorController;
use App\Http\Controllers\Admin\ReservasController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\MasterController;
use App\Models\Inscripcion_Campus;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/historia', function () {
    return view('tetir.historia');
})->middleware('language');

Route::get('/biografia', function () {
    return view('tetir.juan');
})->middleware('language');

Route::get('/email', function () {
    $data = Inscripcion_Campus::find(11);
    return view('Inscripcion_Campus_PDF', compact('data'));
})->middleware('language');

Route::get('/', [MasterController::class, 'home'])->middleware('language');
Route::get('/campus', [MasterController::class, 'campus'])->middleware('language');

Route::get('/contactanos', [MasterController::class, 'contactanos'])->middleware('language')->name('contacto');
Route::post('/contactanos', [MasterController::class, 'contactanosStore'])->middleware('language')->name('contacto.store');;

Route::get('/ficha-jugador', [MasterController::class, 'fichaJugador'])->middleware('language')->name('ficha');
Route::get('/formulario-campus', [MasterController::class, 'formularioCampus'])->middleware('language')->name('insCampus');
Route::get('/noticia/{noticia}', [MasterController::class, 'noticia'])->middleware('language');
Route::get('/noticias', [MasterController::class, 'noticias'])->middleware('language');
Route::get('/reserva', [MasterController::class, 'reserva'])->middleware('language')->name('reserva');
Route::get('/torneo-navidad', [MasterController::class, 'torneoNavidad'])->middleware('language');

Auth::routes();

// Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('language');

//->middleware('language')



// Administración
Route::group(['middleware' => 'auth'], function () {

    Route::get('admin', [HomeController::class, 'index']);

    //Usuarios
    Route::resource('/admin/users', UsersController::class);
    //Noticias
    Route::resource('/admin/noticias', NoticiasController::class)->middleware('language');

    //Galeria
    Route::resource('/admin/carrusel', CarruselController::class)->middleware('language');
    Route::resource('/admin/patrocinadores', PatrocinadorController::class)->middleware('language');
    Route::resource('/admin/galerianavidad', GaleriaNavidadController::class)->middleware('language');

    //Información
    Route::resource('/admin/infonavidad', Info_NavidadController::class)->middleware('language');
    Route::resource('/admin/infocampus', Info_CampusController::class)->middleware('language');
    Route::resource('/admin/inforeserva', Info_ReservaController::class)->middleware('language');

    //Clasificacionesc
    Route::resource('/admin/competicion', CompeticionController::class)->middleware('language');

});

    //Inscripciones
    Route::resource('/admin/reservas', ReservasController::class)->middleware('language');
    Route::resource('/admin/fichasjugador', FichaJugadorController::class)->middleware('language');
    Route::resource('/admin/inscripcionescampus', CampusController::class)->middleware('language');

resources/views/admin/galerias/patrocinadores/create.blade.php
@extends('adminlte::page')

@section('title')

@section('content_header')
    <h1>Crear Patrocinador o Colaborador</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            {!! Form::open(['route' => 'patrocinadores.store', 'files' => true]) !!}
                
                {!! Form::hidden('user_id', auth()->user()->id) !!}

                <div class="form-group">
                    {!! Form::label('nombre', 'Nombre:') !!}
                    {!! Form::text('nombre', null, [ 'class' => 'form-control', 'placeholder' => 'Introduzca el Nombre del Patrocinador']) !!}

                    @error('nombre')
                        <span class="text-danger" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>

                <div class="row mr-3">
                    <div class="col">
                        <div class="image-warp">
                            <img id="picture" src="https://cdn.pixabay.com/photo/2021/02/21/18/48/elks-6037526_1280.jpg"
                                alt="Imagen">
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            {!! Form::label('file', 'Imagen para el Patrocinador') !!}
                            {!! Form::file('file', ['class' => 'form-control', 'accept' => 'image/*']) !!}
                            <h4>Requisistos de la imagen</h4>
                            <p>Para que la imagen se vea bien el la pagina debeta tener:</p>
                            <p>- El tamaño de la imangen debera ser cuadrada, podria ser mas grande pero siguiendo la misma
                                estetica</p>
                            <p>- El peso de la imagen no puede ser superior a 5Mb</p>
                            <p>- Escoja una imagen adecuada</p>
     
                            @error('file')
                                <span class="text-danger" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
     
                </div>
                <br>
                {!! Form::submit('Crear Patrocinador', ['class' => 'btn btn-primary']) !!}
            {!! Form::close() !!}
        </div>
    </div>
@stop

@section('css')
<style>
    .image-warp {
        position: relative;
        padding-bottom: 56.25%
    }

    .image-warp img {
        position: absolute;
        object-fit: cover;
        width: 100%;
        height: 100%;
    }

</style>
@stop

@section('js')
<script src="https://cdn.ckeditor.com/ckeditor5/27.1.0/classic/ckeditor.js"></script>

<script>

    ClassicEditor
    .create( document.querySelector( '#texto' ) )
    .catch( error => {
        console.error( error );
    });

    //Cambiar imagen
    document.getElementById("file").addEventListener('change', cambiarImagen);
 
    function cambiarImagen(event) {
        var file = event.target.files[0];

        var reader = new FileReader();
        reader.onload = (event) => {
            document.getElementById("picture").setAttribute('src', event.target.result);
        };

        reader.readAsDataURL(file);
    }

</script>
@stop

resources/views/admin/galerias/patrocinadores/edit.blade.php
@extends('adminlte::page')

@section('title')

@section('content_header')
    <h1>Editar Patrocinador o Colaborador</h1>
@stop

@section('content')
<div class="card">
    <div class="card-body">
        {!! Form::model($patrocinadore,['route' => ['patrocinadores.update', $patrocinadore], 'files' => true, 'method' => 'put']) !!}
            @csrf
            {!! Form::hidden('user_id', auth()->user()->id) !!}

            <div class="form-group">
                {!! Form::label('nombre', 'Nombre:') !!}
                {!! Form::text('nombre', null, [ 'class' => 'form-control', 'placeholder' => 'Introduzca el Nombre del Patrocinador']) !!}

                @error('nombre')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="row mr-3">
                <div class="col">
                    <div class="image-warp">
                        @if ($patrocinadore->image)
                        <img id="picture" src="{{ asset('storage/'.$patrocinadore->image->url) }}" alt="Imagen">
                    @else
                        <img id="picture" src="https://cdn.pixabay.com/photo/2021/02/21/18/48/elks-6037526_1280.jpg" alt="Imagen">
                    @endif
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        {!! Form::label('file', 'Imagen para el Patrocinador') !!}
                        {!! Form::file('file', ['class' => 'form-control', 'accept' => 'image']) !!}
                        <h4>Requisistos de la imagen</h4>
                        <p>Para que la imagen se vea bien el la pagina debeta tener:</p>
                        <p>- El tamaño de la imangen debera ser cuadrada, podria ser mas grande pero siguiendo la misma
                            estetica</p>
                        <p>- El peso de la imagen no puede ser superior a 5Mb</p>
                        <p>- Escoja una imagen adecuada</p>
 
                        @error('file')
                            <span class="text-danger" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
 
            </div>
            <br>
            {!! Form::submit('Actualizar Patrocinador', ['class' => 'btn btn-primary']) !!}
        {!! Form::close() !!}
    </div>
</div>
@stop

@section('css')
<style>
.image-warp {
    position: relative;
    padding-bottom: 56.25%
}

.image-warp img {
    position: absolute;
    object-fit: cover;
    width: 100%;
    height: 100%;
}

</style>
@stop

@section('js')
<script src="https://cdn.ckeditor.com/ckeditor5/27.1.0/classic/ckeditor.js"></script>

<script>

ClassicEditor
.create( document.querySelector( '#texto' ) )
.catch( error => {
    console.error( error );
});

//Cambiar imagen
document.getElementById("file").addEventListener('change', cambiarImagen);

function cambiarImagen(event) {
    var file = event.target.files[0];

    var reader = new FileReader();
    reader.onload = (event) => {
        document.getElementById("picture").setAttribute('src', event.target.result);
    };

    reader.readAsDataURL(file);
}

</script>
@stop

resources/views/admin/galerias/patrocinadores/index.blade.php
@extends('adminlte::page')

@section('title')

@section('content_header')
    <h1>Patrocinadores y Colaboradores</h1>
@stop

@section('content')
@if (session('info'))
<div class="alert alert-info">
    <strong>{{ session('info')}}</strong>
</div>
@endif

@if (session('create'))
<div class="alert alert-success">
    <strong>{{ session('create')}}</strong>
</div>
@endif

@if (session('destroy'))
<div class="alert alert-danger">
    <strong>{{ session('destroy')}}</strong>
</div>
@endif

<div class="card">
    <div class="card-body">
    <a href="{{ route('patrocinadores.create')}}" class="btn btn-success float-right">Nuevo Patrocinador</a>

        <form action="{{ route('patrocinadores.index')}}" method="GET">
            @csrf
            <div class="form-row">
                <div class="col-auto">
                    <input type="submit" class="btn btn-info" value="Buscar">
                </div>
            
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="texto" placeholder="Busque por el Nombre" value="{{$texto}}">
                </div>
            </div>
        </form>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th colspan="3"></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($patrocinadore as $patrocinadores)
                    <tr>
                        <td>{{ $patrocinadores->id }}</td>
                        <td>{{ $patrocinadores->nombre }}</td>
                        <td class="text-right"><a href="{{ route('patrocinadores.edit',$patrocinadores)}}" class="btn btn-primary"><i class="fas fa-edit"></i></a></td>
                        <td class="text-right">
                            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="{{'#exampleModalCenter'.$patrocinadores->id}}">
                                <i class="fas fa-trash"></i>
                              </button>

                                <!-- Modal -->
                                    <div class="modal fade" id="{{'exampleModalCenter'.$patrocinadores->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLongTitle">Confirmar Borrado</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                    </div>
                                                    <div class="modal-body">
                                                    ¿Está seguro de que quiere borrar al patrocinador "{{ $patrocinadores->nombre }}"?
                                                    </div>
                                                    <div class="modal-footer">
                                                    <button type="button" class="btn btn-success" data-dismiss="modal">Cancelar</button>

                                                    <form action="{{ route('patrocinadores.destroy', $patrocinadores)}}" method="POST">
                                                        @csrf
                                                        @method('delete')
                                                        <button type="submit" class="btn btn-danger">Aceptar</button>
                                                    </form>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                <!-- Fin Modal -->
                        </td>
                        
                    </tr>
                    
                @endforeach
            </tbody>
        </table>
        {{ $patrocinadore->links() }}
    </div>
</div>
@stop