routes/web.php
<?php

use App\Http\Controllers\Admin\CampusController;
use App\Http\Controllers\Admin\CarruselController;
use App\Http\Controllers\Admin\CompeticionController;
use App\Http\Controllers\Admin\FichaJugadorController;
use App\Http\Controllers\Admin\GaleriaNavidadController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\Info_CampusController;
use App\Http\Controllers\Admin\Info_NavidadController;
use App\Http\Controllers\Admin\Info_ReservaController;
use App\Http\Controllers\Admin\NoticiasController;
use App\Http\Controllers\Admin\PatrocinadorController;
use App\Http\Controllers\Admin\ReservasController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\MasterController;
use App\Models\Inscripcion_Campus;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/historia', function () {
    return view('tetir.historia');
})->middleware('language');

Route::get('/biografia', function () {
    return view('tetir.juan');
})->middleware('language');

Route::get('/email', function () {
    $data = Inscripcion_Campus::find(11);
    return view('Inscripcion_Campus_PDF', compact('data'));
})->middleware('language');

Route::get('/', [MasterController::class, 'home'])->middleware('language');
Route::get('/campus', [MasterController::class, 'campus'])->middleware('language');

Route::get('/contactanos', [MasterController::class, 'contactanos'])->middleware('language')->name('contacto');
Route::post('/contactanos', [MasterController::class, 'contactanosStore'])->middleware('language')->name('contacto.store');;

Route::get('/ficha-jugador', [MasterController::class, 'fichaJugador'])->middleware('language')->name('ficha');
Route::get('/formulario-campus', [MasterController::class, 'formularioCampus'])->middleware('language')->name('insCampus');
Route::get('/noticia/{noticia}', [MasterController::class, 'noticia'])->middleware('language');
Route::get('/noticias', [MasterController::class, 'noticias'])->middleware('language');
Route::get('/reserva', [MasterController::class, 'reserva'])->middleware('language')->name('reserva');
Route::get('/torneo-navidad', [MasterController::class, 'torneoNavidad'])->middleware('language');

Auth::routes();

// Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home')->middleware('language');

//->middleware('language')



// Administración
Route::group(['middleware' => 'auth'], function () {

    Route::get('admin', [HomeController::class, 'index']);

    //Usuarios
    Route::resource('/admin/users', UsersController::class);
    //Noticias
    Route::resource('/admin/noticias', NoticiasController::class)->middleware('language');

    //Galeria
    Route::resource('/admin/carrusel', CarruselController::class)->middleware('language');
    Route::resource('/admin/patrocinadores', PatrocinadorController::class)->middleware('language');
    Route::resource('/admin/galerianavidad', GaleriaNavidadController::class)->middleware('language');

    //Información
    Route::resource('/admin/infonavidad', Info_NavidadController::class)->middleware('language');
    Route::resource('/admin/infocampus', Info_CampusController::class)->middleware('language');
    Route::resource('/admin/inforeserva', Info_ReservaController::class)->middleware('language');

    //Clasificacionesc
    Route::resource('/admin/competicion', CompeticionController::class)->middleware('language');

});

    //Inscripciones
    Route::resource('/admin/reservas', ReservasController::class)->middleware('language');
    Route::resource('/admin/fichasjugador', FichaJugadorController::class)->middleware('language');
    Route::resource('/admin/inscripcionescampus', CampusController::class)->middleware('language');

app/Http/Controllers/Admin/ReservasController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Exports\ReservasExport;
use App\Http\Controllers\Controller;
use App\Http\Requests\ReservaRequest;
use App\Models\Reserva_Plaza;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Barryvdh\DomPDF\Facade as PDF;
use Maatwebsite\Excel\Facades\Excel;

class ReservasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $texto = trim($request->get('texto'));
        $reserva = Reserva_Plaza::where('nombre', 'LIKE','%'.$texto.'%')->orderBy('created_at', 'desc')->paginate(10);
        return view('admin.inscripciones.reserva.index', compact('reserva', 'texto'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return Excel::download(new ReservasExport, 'Reservas.xlsx');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ReservaRequest $request)
    {
        $reserva = Reserva_Plaza::create($request->all());
        if ($request->file('file')) {
            $url = Storage::put('img',$request->file('file'));

            $reserva->image()->create([
                'url' => $url
            ]);
        }

        return redirect()->route('reserva', $reserva)->with('create','Se ha enviado la reserva');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Reserva_Plaza $reserva)
    {
        $data = $reserva;
        $pdf = PDF::loadView('Reserva_PDF', compact('data'));
        $pdfD = $pdf->download('Reserva.pdf');

        return $pdfD;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Reserva_Plaza $reserva)
    {
        $reserva->delete();

        return redirect()->route('reservas.index')->with('destroy','Reserva Borrada');
    }
}

resources/views/admin/inscripciones/reserva/index.blade.php
@extends('adminlte::page')

@section('title')

@section('content_header')
    <h1>Reservas</h1>
@stop

@section('content')

@if (session('info'))
    <div class="alert alert-info">
        <strong>{{ session('info')}}</strong>
    </div>
@endif

@if (session('destroy'))
    <div class="alert alert-danger">
        <strong>{{ session('destroy')}}</strong>
    </div>
@endif
    
    <div class="card">
        <div class="card-body">
            <a href="{{ route('reservas.create')}}" class="btn btn-success btn-lg float-right"><i class="fas fa-file-csv"></i></a>
            <form action="{{ route('reservas.index')}}" method="GET">
                @csrf
                <div class="form-row">
                    <div class="col-auto">
                        <input type="submit" class="btn btn-info" value="Buscar">
                    </div>
                
                    <div class="col-sm-4">
                        <input type="text" class="form-control" name="texto" placeholder="Busque por Nombre" value="{{$texto}}">
                    </div>
                </div>
            </form>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Telf. Tutor</th>
                        <th>Fecha de Nacimiento</th>
                        <th colspan="2"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($reserva as $reservas)
                        <tr>
                            <td>{{ $reservas->id }}</td>
                            <td>{{ $reservas->nombre }}</td>
                            <td>{{ $reservas->telf_tutor }}</td>
                            <td>{{ $reservas->fecha_nacimiento }}</td>
                            <td><a href="{{ route('reservas.edit', $reservas)}}" class="btn btn-primary"><i class="fas fa-file-pdf"></i></i></a></td>
                            <td>
                                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="{{'#exampleModalCenter'.$reservas->id}}">
                                    <i class="fas fa-trash"></i>
                                  </button>

                                    <!-- Modal -->
                                        <div class="modal fade" id="{{'exampleModalCenter'.$reservas->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLongTitle">Confirmar Borrado</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                        </div>
                                                        <div class="modal-body">
                                                        ¿Está seguro de que quiere borrar la noticia "{{ $reservas->nombre }}"?
                                                        </div>
                                                        <div class="modal-footer">
                                                        <button type="button" class="btn btn-success" data-dismiss="modal">Cancelar</button>

                                                        <form action="{{ route('reservas.destroy', $reservas)}}" method="POST">
                                                            @csrf
                                                            @method('delete')
                                                            <button type="submit" class="btn btn-danger">Aceptar</button>
                                                        </form>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    <!-- Fin Modal -->
                            </td>
                            
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $reserva->links() }}
        </div>
    </div>

@stop